---
- hosts: seconion 
  gather_facts: false
  vars:
    ansible_connection: ssh
    ansible_user: defender 
    ansible_ssh_pass: "{{ ansible.password }}"
    ansible_become_pass: "{{ ansible.password }}"
  become: yes
  roles:
    - user_provision
